apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: proxmox-exporter
    app.kubernetes.io/component: exporter
    release: prometheus
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9221
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: proxmox-exporter
